### ISSUE TITLE
the landing page should be redirected to report if the user is currently logged-in

### ISSUE THREAD

**Issue by thinkinginmath** [stack360/statusreport#22] opened 2017-04-14 17:53 UTC
@xichengc 
 Chrome,
1) Go to the page and use Google login, after login, the page is redirected to http://www.myweeklystatus.com/ui/report/index#

2) Open a new tab, and type in http://www.myweeklystatus.com/. It is redirected to http://www.myweeklystatus.com/ui/login
The code should be smart enough to detect that the user is already logged-in and should directly show http://www.myweeklystatus.com/ui/report/index#

e.g, take a reference of Gmail or Google user experience. No need to login if there are active sessions in the current browser.

**Comment by xichengc** [comment] 2017-04-14 18:04
I wrote a mechanism to check if user is currently logged-in.
I am not able to reproduce your issue on Chrome: I logged in in one tab and open a second tab and enter http://www.myweeklystatus.com and it redirected me to the report index page instead of asking me to log in again.

**Comment by xichengc** [comment] 2017-04-20 18:11
@weidongshao This issue cannot be reproduced and the landing page is always redirected to report if user is currently logged-in. I am closing this issue.

**Closed as completed by xichengc** 2017-04-20 18:11 UTC
